image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: registry.gitlab.com/$CI_PROJECT_PATH/app:latest

stages:
  - build
  - push

build-image:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_NAME .
    - docker images

push-image:
  stage: push
  script:
    - docker push $IMAGE_NAME
